### ISSUE TITLE
Cannot see even a single example without Marionette

### ISSUE THREAD

**Issue by thetutlage** [d4f/backbone-router#31]
Cannot see even a single example without Marionette

**Comment by RasCarlito** [comment]
That's correct =(
I am re-writing the documentations with focus on usage without Marionette.
It will be done soon.

In the meantime, I am preparing a complete code example without Marionette for you.
I'll get back to you shortly =)

**Comment by RasCarlito** [comment]
Library has been renamde to backbone-highway : https://github.com/d4f/backbone-highway.git
All examples are plain Backbone.
